src/Entity/Statistics.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\StatisticsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StatisticsRepository::class)]
class Statistics
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int $id;

    #[ORM\ManyToOne(inversedBy: 'statistics')]
    #[ORM\JoinColumn(nullable: false)]
    private Team $team;

    #[ORM\Column]
    private int $goalsInTime;

    #[ORM\Column]
    private int $goalsInOvertime;

    #[ORM\Column]
    private int $goalsLostInTime;

    #[ORM\Column]
    private int $goalsLostInOvertime;

    #[ORM\Column]
    private int $points;

    #[ORM\Column]
    private bool $win;

    #[ORM\Column]
    private bool $overtime;

    public function __construct(
        Team $team,
        int $goalsInTime,
        int $goalsInOvertime,
        int $goalsLostInTime,
        int $goalsLostInOvertime,
        int $points,
        bool $win,
        bool $overtime,
    ) {
        $this->team = $team;
        $team->addStatistic($this);
        $this->goalsInTime = $goalsInTime;
        $this->goalsInOvertime = $goalsInOvertime;
        $this->goalsLostInTime = $goalsLostInTime;
        $this->goalsLostInOvertime = $goalsLostInOvertime;
        $this->points = $points;
        $this->win = $win;
        $this->overtime = $overtime;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getTeam(): Team
    {
        return $this->team;
    }

    public function getGoalsInTime(): int
    {
        return $this->goalsInTime;
    }

    public function getGoalsInOvertime(): int
    {
        return $this->goalsInOvertime;
    }

    public function getGoals(): int
    {
        return $this->goalsInTime + $this->goalsInOvertime;
    }

    public function getPoints(): int
    {
        return $this->points;
    }

    public function isWin(): bool
    {
        return $this->win;
    }

    public function isOvertime(): bool
    {
        return $this->overtime;
    }

    public function getGoalsLostInTime(): int
    {
        return $this->goalsLostInTime;
    }

    public function getGoalsLostInOvertime(): int
    {
        return $this->goalsLostInOvertime;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>{% block title %}2. PD{% endblock %}</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}
        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>

    <body id="{% block body_id %}{% endblock %}">

        {% block header %}
            <header>
                <div class="navbar navbar-default navbar-static-top" role="navigation">
                    <div class="container">
                        <div class="navbar-header col-md-3 col-lg-2">
                            <a class="navbar-brand" href="{{ path('homepage') }}">
                                2. PD
                            </a>

                            <button type="button" class="navbar-toggle"
                                    data-toggle="collapse"
                                    data-target=".navbar-collapse">
                                <span class="sr-only">Menu</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav navbar-right">
                                {% block header_navigation_links %}
                                    <li>
                                        <a href="{{ path('homepage') }}">
                                            <i class="fa fa-home" aria-hidden="true"></i> Home
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ path('teams') }}">
                                            <i class="fa fa-futbol" aria-hidden="true"></i> Teams
                                        </a>
                                    </li>
                                {% endblock %}
                            </ul>
                        </div>
                    </div>
                </div>
            </header>
        {% endblock %}

        <div class="container body-container">
            {% block body %}
                <div class="row">
                    <div id="main" class="col-sm-9">
                        {% block main %}{% endblock %}
                    </div>
                    <div id="sidebar" class="col-sm-3">
                        {% block sidebar %}
                        {% endblock %}
                    </div>
                </div>
            {% endblock %}
        </div>
    </body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block main %}
    <h1>Komandas</h1>
    <table class="table table-striped table-middle-aligned table-hover">
        <thead>
        <tr>
            <th scope="col">Vieta</th>
            <th scope="col">Komandas nosaukums</th>
            <th scope="col">Punkti</th>
            <th scope="col">Uzvaras pamatlaikā</th>
            <th scope="col">Zaudējumi pamatlaikā</th>
            <th scope="col">Uzvaras papildlaikā</th>
            <th scope="col">Zaudējumi papildlaikā</th>
            <th scope="col">Gūtie vārti</th>
            <th scope="col">Zaudētie vārti</th>
        </tr>
        </thead>
        <tbody>
            {% for stat in statistics %}
                <tr>
                    <td>{{ stat.place }}</td>
                    <td>{{ stat.name }}</td>
                    <td class="text-center">{{ stat.points }}</td>
                    <td class="text-center">{{ stat.onTimeWins }}</td>
                    <td class="text-center">{{ stat.onTimeLoses }}</td>
                    <td class="text-center">{{ stat.overTimeWins }}</td>
                    <td class="text-center">{{ stat.overTimeLoses }}</td>
                    <td class="text-center">{{ stat.goalsScored }}</td>
                    <td class="text-center">{{ stat.goalsLost }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">Rezultāti nav pieejami, ielādē failus, lai aprēķinātu jaunus rezultātus</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <h1>Spēlētāji</h1>
    <table class="table table-striped table-middle-aligned table-hover">
        <thead>
        <tr>
            <th scope="col">Vieta</th>
            <th scope="col">Vārds</th>
            <th scope="col">Uzvārds</th>
            <th scope="col">Nr</th>
            <th scope="col">Komanda</th>
            <th scope="col">Gūtie vārti</th>
            <th scope="col">Rezultatīvās piespēles</th>
        </tr>
        </thead>
        <tbody>
            {% for stat in players %}
                <tr>
                    <td>{{ stat.place }}</td>
                    <td>{{ stat.firstName }}</td>
                    <td>{{ stat.lastName }}</td>
                    <td class="text-center">{{ stat.number }}</td>
                    <td>{{ stat.team }}</td>
                    <td class="text-center">{{ stat.goals }}</td>
                    <td class="text-center">{{ stat.assists }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">Spēlētēju statistika nav pieejama</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <h1>Rupjākie spēlētāji</h1>
    <table class="table table-striped table-middle-aligned table-hover">
        <thead>
        <tr>
            <th scope="col">Vieta</th>
            <th scope="col">Vārds</th>
            <th scope="col">Uzvārds</th>
            <th scope="col">Nr</th>
            <th scope="col">Komanda</th>
            <th scope="col">Sodu skaits</th>
        </tr>
        </thead>
        <tbody>
            {% for stat in rude_players %}
                <tr>
                    <td>{{ stat.place }}</td>
                    <td>{{ stat.firstName }}</td>
                    <td>{{ stat.lastName }}</td>
                    <td class="text-center">{{ stat.number }}</td>
                    <td>{{ stat.team }}</td>
                    <td class="text-center">{{ stat.penalties }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">Spēlētēju statistika nav pieejama</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block sidebar %}
    <div class="section actions">
        <a href="{{ path('upload') }}" class="btn btn-lg btn-block btn-success">
            <i class="fa fa-plus" aria-hidden="true"></i> Pievienot failus
        </a>
    </div>

    {{ parent() }}
{% endblock %}

templates/teams.html.twig
{% extends 'base.html.twig' %}

{% block main %}
<div data-controller="teams">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist" data-teams-target="tablist">
        {% for team in teams %}
            <li role="presentation" class="{{ loop.first ? 'active' : '' }}">
                <a href="#{{ team.name }}" aria-controls="{{ team.name }}" role="tab"
                   data-toggle="tab">{{ team.name }}</a>
            </li>
        {% else %}
            <li role="presentation" class="active">
                <a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a>
            </li>
        {% endfor %}
    </ul>
    <!-- Tab panes -->
    <div class="tab-content" data-teams-target="tabcontent">
        {% for team in teams %}
        <div role="tabpanel" class="tab-pane {{ loop.first ? 'active' : '' }}" id="{{ team.name }}">
            <h3>{{ team.name }}</h3>
            <br>
            <h4>Spēlētāji</h4>
            <table class="table table-striped table-middle-aligned table-hover">
                <thead>
                    <tr>
                        <th scope="col">Nr</th>
                        <th scope="col">Vārds</th>
                        <th scope="col">Uzvārds</th>
                        <th scope="col">Spēlētas spēles</th>
                        <th scope="col">Spēlētās spēles pamatsastāvā</th>
                        <th scope="col">Gūtie vārti</th>
                        <th scope="col">Rezultatīvās piespēles</th>
                        <th scope="col">Spēlētās minūtes</th>
                        <th scope="col">Dzeltenās kartītes</th>
                        <th scope="col">Sarkanās kartītes</th>
                    </tr>
                </thead>
                <tbody>
                {% for stat in playerStats[team.id] %}
                    <tr>
                        <td class="text-center">{{ stat.number }}</td>
                        <td>{{ stat.firstName }}</td>
                        <td>{{ stat.lastName }}</td>
                        <td class="text-center">{{ stat.gamesPlayed }}</td>
                        <td class="text-center">{{ stat.coreGamesPlayed }}</td>
                        <td class="text-center">{{ stat.goals }}</td>
                        <td class="text-center">{{ stat.assists }}</td>
                        <td class="text-center">{{ stat.minutes ~ ':' ~ stat.seconds }}</td>
                        <td class="text-center">{{ stat.yellow }}</td>
                        <td class="text-center">{{ stat.red }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="10">Spēlētēju statistika nav pieejama</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <h4>Vārtsargi</h4>
            <table class="table table-striped table-middle-aligned table-hover">
                <thead>
                    <tr>
                        <th scope="col">Nr</th>
                        <th scope="col">Vārds</th>
                        <th scope="col">Uzvārds</th>
                        <th scope="col">Spēlētas spēles</th>
                        <th scope="col">Ielaistie vārti</th>
                        <th scope="col">Vidēji vienā spēlē ielaistie vārti</th>
                    </tr>
                </thead>
                <tbody>
                {% for stat in goalieStats[team.id] %}
                    <tr>
                        <td class="text-center">{{ stat.number }}</td>
                        <td>{{ stat.firstName }}</td>
                        <td>{{ stat.lastName }}</td>
                        <td class="text-center">{{ stat.gamesPlayed }}</td>
                        <td class="text-center">{{ stat.goalsAgainst }}</td>
                        <td class="text-center">{{ stat.averageGoalsAgainst }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="10">Spēlētēju statistika nav pieejama</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
            <div role="tabpanel" class="tab-pane active" id="home">Nav komandu datu.</div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/upload.html.twig
{% extends 'base.html.twig' %}

{% block main %}
    <h1>Pievieno failus</h1>
    <p>Failiem jābūt JSON formātā</p>
    {{ form_start(form, {attr: attr|default({})}) }}
    {{ form_widget(form) }}

    <button type="submit" class="{{ button_css|default("btn btn-primary") }}">
        <i class="fa fa-save" aria-hidden="true"></i> Pievienot failus
    </button>
    {{ form_end(form) }}
{% endblock %}